
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
toolchain = "nightly-2022-08-01"
docker_image = "thewawar/ckb-capsule:2022-08-01"

# capsule version
version = "0.8.0"
# path of deployment config file
deployment = "deployment.toml"

[rust]
workspace_dir = "contracts"

[[contracts]]
name = "ckb-std-tests"
template_type = "Rust"

[[contracts]]
name = "exec-callee"
template_type = "Rust"

[[contracts]]
name = "exec-caller"
template_type = "Rust"

[[contracts]]
name = "exec-caller-by-code-hash"
template_type = "Rust"
