[package]
name = "ckb-std"
version = "0.2.1"
authors = ["jjy <jjyruby@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/jjyr/ckb-std"
description = "This library contains serveral modules help you write CKB contract with Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["buddy-alloc"]
libc = []

[build-dependencies]
cc = "1.0"

[dependencies]
buddy-alloc = { version = "0.2.0", optional = true }
